name: learning-githubrunner

on:
    workflow_dispatch:

jobs:
  learning-test:
        container: cuaesd/aesd-autotest:unit-test
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Run unit test
            run: echo "Hello"
          - name: Create dir
            run: mkdir newdir
        
