name: learning-githubrunner

on:
    workflow_dispatch:

jobs:
  learning-test:
        container:
          image: ubuntu
          volumes:
            - /tmp/aeld:/debug
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Run unit test
            run: echo "Hello"
          - name: Create dir
            run: mkdir newdir
          - name: List volumens created
            run: ls /; ls /debug        
